# Generated by Django 4.0.5 on 2022-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubofaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=300)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
